### ISSUE TITLE
adding additional players to the eww music widget

### ISSUE THREAD

**Issue by anchovyyy** [niraj998/dotfiles#3]
Hi, I want the music player to be able to see stuff player on my browser (brave), how would I go about this?

**Comment by niraj998** [comment]
Honestly I designed script to not include brave, because whenever I'm watching youtube the name of title would show up in the widgets.

You need to modify (.config/eww/scripts/music) this script to add that.
Near the top of script find these lines

Control="MPD"
[ -n "$(pgrep spotify)" ] && Control="spotify" 



add this to the next line
[ -n "$(pgrep brave)" ] && Control="brave"
OR If your name of the package is brave-bin
[ -n "$(pgrep brave-bin)" ] && Control="brave-bin"

You can add any of the players you want like I mentioned above. 


Incase this doesn't work here's how to debug, first of all stop all the music players and close them
1. start only one player you want
2. run  `pgrep Youraudioplayername` 
3. if you get result for above command then this line is correct [ -n "$(pgrep Youraudioplayername)" ] 
4. run `playerctl -l`
5. whaterver output you get from this should be mentioned here Control="audioplayer"

**Comment by anchovyyy** [comment]
Thank you this is exactly what I was looking for, the problem was that I didn't write brave-bin!
